// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function GetQuote():Promise<database.Quote>;

export function Greet(arg1:string):Promise<string>;
